import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const ctx=vm.createContext({});vm.runInContext(fs.readFileSync('public/modules/lab-engine.js','utf8')+';globalThis.engine=LabEngine',ctx);const E=ctx.engine;
const bars=Array.from({length:100},(_,i)=>({t:1700000000+i*3600,o:100+i,h:102+i,l:98+i,c:101+i,v:100}));
assert.equal(E.normalize(bars).length,100);
assert.throws(()=>E.normalize([...bars.slice(0,99),bars[98]]),/duplicati/);
assert.equal(E.indicator(bars,'sma',20)[19],110.5);
assert.equal(E.indicator(bars,'rsi',14)[30],100);
assert.equal(E.indicator(bars.map(b=>({...b,v:null})),'volume',14)[30],null);
const cfg={rules:[{left:'close',period:14,op:'gt',right:'number',rightPeriod:14,value:0}],direction:'long',stop:1,take:1,cost:2,quantity:1};
const result=E.run(bars,cfg);
assert.equal(result.trades[0].entry,bars[1].o);
assert.equal(result.trades[0].reason,'Stop'); // both stop and target touched
assert.ok(result.trades[0].pnl < -1);
assert.equal(result.train.n+result.holdout.n,result.stats.n);
const prefix=E.indicator(bars.slice(0,60),'ema',20),full=E.indicator(bars,'ema',20);
assert.deepEqual(prefix,full.slice(0,60));
const gap=bars.map(b=>({...b}));gap[1]={...gap[1],o:100,h:100.5,l:99.5,c:100};gap[2]={...gap[2],o:90,h:91,l:89,c:90};
assert.equal(E.run(gap,{...cfg,stop:5,take:5}).trades[0].exit,90);
console.log('Lab engine: 10 assertions passed');
const flat=bars.map((b)=>({...b,o:100,h:100,l:100,c:100}));
assert.equal(E.indicator(flat,'adx',14)[40],0);
assert.equal(E.indicator(bars,'adx',14)[40],100);
assert.equal(E.indicator(flat,'macdHist',14)[40],0);
for(const key of ['rsi','atr','adx','macd','cci','obv'])assert.deepEqual(E.indicator(bars.slice(0,60),key,14),E.indicator(bars,key,14).slice(0,60));
assert.equal(E.run(bars,{...cfg,rules:[{...cfg.rules[0],value:1e9}]}).stats.n,0);
assert.equal(E.run(bars,{...cfg,direction:'short'}).trades[0].reason,'Stop');
assert.throws(()=>E.run(bars,{...cfg,rules:[]}),/regole/);
assert.throws(()=>E.run(bars,{...cfg,take:120}),/Parametri/);
console.log('Additional checks passed: ADX/MACD, causality, short, empty signals, validation');
